openapi: 3.0.3
info:
    title: Character Service API
    description: TODO character API
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /character:
        get:
            tags:
                - character
            summary: list character
            description: List all stored bottles
            operationId: character#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredCharacterResponseTinyCollection'
                            example:
                                - experience: 65.21
                                  health: 12.6
                                  id: 123abc
                                  name: Arc Warden
                                - experience: 65.21
                                  health: 12.6
                                  id: 123abc
                                  name: Arc Warden
                                - experience: 65.21
                                  health: 12.6
                                  id: 123abc
                                  name: Arc Warden
                                - experience: 65.21
                                  health: 12.6
                                  id: 123abc
                                  name: Arc Warden
        post:
            tags:
                - character
            summary: add character
            description: Add new character and return its ID.
            operationId: character#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            description: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                            experience: 65.21
                            health: 12.6
                            name: Arc Warden
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Animi doloribus consectetur ea odio qui.
                            example: Veniam cumque commodi nesciunt cumque architecto repellendus.
    /character/{id}:
        delete:
            tags:
                - character
            summary: remove character
            description: Remove character
            operationId: character#remove
            parameters:
                - name: id
                  in: path
                  description: ID of character to remove
                  required: true
                  schema:
                    type: string
                    description: ID of character to remove
                    example: Sit id accusantium.
                  example: Est eius ipsa.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - character
            summary: show character
            description: Show character by Id
            operationId: character#show
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: tiny
                    enum:
                        - default
                        - tiny
                  example: tiny
                - name: id
                  in: path
                  description: ID of character to show
                  required: true
                  schema:
                    type: string
                    description: ID of character to show
                    example: Exercitationem officiis.
                  example: Vel itaque animi est.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredCharacterResponseTiny'
                                $ref: '#/components/schemas/StoredCharacter'
                            example:
                                description: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                                experience: 65.21
                                health: 12.6
                                id: 123abc
                                name: Arc Warden
                "404":
                    description: 'not_found: Character not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
        put:
            tags:
                - character
            summary: update character
            description: ' update '
            operationId: character#update
            parameters:
                - name: id
                  in: path
                  description: ID of character to update
                  required: true
                  schema:
                    type: string
                    description: ID of character to update
                    example: Animi a in perferendis incidunt.
                  example: Quibusdam labore officia.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            character:
                                description: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                                experience: 65.21
                                health: 12.6
                                name: Arc Warden
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredCharacterResponseTiny'
                                $ref: '#/components/schemas/StoredCharacter'
                            example:
                                description: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                                experience: 65.21
                                health: 12.6
                                id: 123abc
                                name: Arc Warden
    /inventory/{id}:
        delete:
            tags:
                - inventory
            summary: remove inventory
            description: Remove Inventory
            operationId: inventory#remove
            parameters:
                - name: id
                  in: path
                  description: ID of inventory to remove
                  required: true
                  schema:
                    type: string
                    description: ID of inventory to remove
                    example: Inventore ea similique necessitatibus.
                  example: Debitis est officiis cumque et.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - inventory
            summary: show inventory
            description: Show inventory by Id
            operationId: inventory#show
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: tiny
                    enum:
                        - default
                        - tiny
                  example: tiny
                - name: id
                  in: path
                  description: ID of inventory to show
                  required: true
                  schema:
                    type: string
                    description: ID of inventory to show
                    example: Excepturi nostrum.
                  example: Vitae itaque.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredInventoryResponseTiny'
                                $ref: '#/components/schemas/StoredInventory'
                            example:
                                characterId: 123abc
                                id: 123abc
                                items:
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                "404":
                    description: 'not_found: Character not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
    /inventory/{id}/item:
        get:
            tags:
                - inventory
            summary: showItem inventory
            description: Show items in an inventory
            operationId: inventory#showItem
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: tiny
                    enum:
                        - default
                        - tiny
                  example: tiny
                - name: id
                  in: path
                  description: ID of inventory to show
                  required: true
                  schema:
                    type: string
                    description: ID of inventory to show
                    example: Quod et at minus non nostrum quos.
                  example: Perspiciatis voluptas.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItemResponseTinyCollection'
                            example:
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
                "404":
                    description: 'not_found: Character not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
    /inventory/{id}/item/{itemId}:
        delete:
            tags:
                - inventory
            summary: removeItem inventory
            description: Remove an item from inventory
            operationId: inventory#removeItem
            parameters:
                - name: id
                  in: path
                  description: ID of inventory to add
                  required: true
                  schema:
                    type: string
                    description: ID of inventory to add
                    example: Eum cupiditate exercitationem suscipit.
                  example: Dolorem numquam eveniet similique dolor sed.
                - name: itemId
                  in: path
                  description: ID of item to add
                  required: true
                  schema:
                    type: string
                    description: ID of item to add
                    example: Ea molestias molestiae dolorum ipsa nulla.
                  example: Dolor earum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredInventoryResponseTiny'
                                $ref: '#/components/schemas/StoredInventory'
                            example:
                                characterId: 123abc
                                id: 123abc
                                items:
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
        post:
            tags:
                - inventory
            summary: addItem inventory
            description: Add new item to inventory.
            operationId: inventory#addItem
            parameters:
                - name: id
                  in: path
                  description: ID of inventory to add
                  required: true
                  schema:
                    type: string
                    description: ID of inventory to add
                    example: Blanditiis veniam ex nam ex.
                  example: Ipsa quis exercitationem iste harum.
                - name: itemId
                  in: path
                  description: ID of item to add
                  required: true
                  schema:
                    type: string
                    description: ID of item to add
                    example: Delectus molestiae ut expedita dolore eos.
                  example: Ut hic.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddItemRequestBody'
                        example:
                            view: default
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredInventoryResponseTiny'
                                $ref: '#/components/schemas/StoredInventory'
                            example:
                                characterId: 123abc
                                id: 123abc
                                items:
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
    /inventory/character/{characterId}:
        get:
            tags:
                - inventory
            summary: list inventory
            description: List all items in character inventory
            operationId: inventory#list
            parameters:
                - name: characterId
                  in: path
                  description: ID of character to show
                  required: true
                  schema:
                    type: string
                    description: ID of character to show
                    example: Eveniet ex praesentium.
                  example: Aut ut consequuntur.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredInventoryResponseTinyCollection'
                            example:
                                - characterId: 123abc
                                  id: 123abc
                                  items:
                                    - damage: 37.8267
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                - characterId: 123abc
                                  id: 123abc
                                  items:
                                    - damage: 37.8267
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                - characterId: 123abc
                                  id: 123abc
                                  items:
                                    - damage: 37.8267
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
                                    - damage: 37.8267
                                      healing: 12.6
                                      id: 123abc
                                      name: Boots of travel
                                      protection: 65.21
        post:
            tags:
                - inventory
            summary: add inventory
            description: Add new inventory and return its ID.
            operationId: inventory#add
            parameters:
                - name: characterId
                  in: path
                  description: ID of character to show
                  required: true
                  schema:
                    type: string
                    description: ID of character to show
                    example: Rem magni veniam velit est magni.
                  example: Officia tempora hic ab.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Est maiores commodi perferendis vel molestias.
                            example: Voluptatum modi.
    /item:
        get:
            tags:
                - item
            summary: list item
            description: List all stored items
            operationId: item#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItemResponseTinyCollection'
                            example:
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
                                - damage: 37.8267
                                  healing: 12.6
                                  id: 123abc
                                  name: Boots of travel
                                  protection: 65.21
        post:
            tags:
                - item
            summary: add item
            description: Add new item and return its ID.
            operationId: item#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody2'
                        example:
                            damage: 37.8267
                            description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                            healing: 12.6
                            name: Boots of travel
                            protection: 65.21
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Enim nihil sit ex.
                            example: Ut veniam dolores.
    /item/{id}:
        delete:
            tags:
                - item
            summary: remove item
            description: Remove character
            operationId: item#remove
            parameters:
                - name: id
                  in: path
                  description: ID of item to remove
                  required: true
                  schema:
                    type: string
                    description: ID of item to remove
                    example: Itaque beatae unde dolor.
                  example: Et ex aperiam dolore omnis.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - item
            summary: show item
            description: Show character by Id
            operationId: item#show
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: default
                    enum:
                        - default
                        - tiny
                  example: tiny
                - name: id
                  in: path
                  description: ID of item to show
                  required: true
                  schema:
                    type: string
                    description: ID of item to show
                    example: Consequatur hic ullam.
                  example: Ipsa est et doloremque reprehenderit quas.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredItemResponseTiny'
                                $ref: '#/components/schemas/JSON'
                            example:
                                damage: 37.8267
                                description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                healing: 12.6
                                id: 123abc
                                name: Boots of travel
                                protection: 65.21
                "404":
                    description: 'not_found: Character not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
        put:
            tags:
                - item
            summary: update item
            description: ' update '
            operationId: item#update
            parameters:
                - name: id
                  in: path
                  description: ID of item to update
                  required: true
                  schema:
                    type: string
                    description: ID of item to update
                    example: Quia explicabo reprehenderit itaque amet quia.
                  example: Maxime quo.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody2'
                        example:
                            item:
                                damage: 37.8267
                                description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                healing: 12.6
                                name: Boots of travel
                                protection: 65.21
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredItemResponseTiny'
                                $ref: '#/components/schemas/JSON'
                            example:
                                damage: 37.8267
                                description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                                healing: 12.6
                                id: 123abc
                                name: Boots of travel
                                protection: 65.21
    /swagger/swagger.json:
        get:
            tags:
                - swagger
            summary: Download gen/http/openapi.json
            description: JSON document containing the API swagger definition
            operationId: swagger#/swagger/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        AddItemRequestBody:
            type: object
            properties:
                view:
                    type: string
                    description: View to render
                    example: default
                    enum:
                        - default
                        - tiny
            example:
                view: default
        AddRequestBody:
            type: object
            properties:
                description:
                    type: string
                    description: Description
                    example: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                experience:
                    type: number
                    description: Experience
                    example: 65.21
                    format: double
                health:
                    type: number
                    description: Health
                    example: 12.6
                    format: double
                name:
                    type: string
                    description: Name
                    example: Arc Warden
            example:
                description: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                experience: 65.21
                health: 12.6
                name: Arc Warden
            required:
                - name
                - health
                - experience
        AddRequestBody2:
            type: object
            properties:
                damage:
                    type: number
                    description: Damage
                    default: 0
                    example: 37.8267
                    format: double
                description:
                    type: string
                    description: Description
                    example: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                healing:
                    type: number
                    description: Healing
                    default: 0
                    example: 12.6
                    format: double
                name:
                    type: string
                    description: Name
                    example: Boots of travel
                protection:
                    type: number
                    description: Protection
                    default: 0
                    example: 65.21
                    format: double
            example:
                damage: 37.8267
                description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                healing: 12.6
                name: Boots of travel
                protection: 65.21
            required:
                - name
                - damage
                - healing
                - protection
        JSON:
            type: object
            properties:
                damage:
                    type: number
                    description: Damage
                    default: 0
                    example: 37.8267
                    format: double
                description:
                    type: string
                    description: Description
                    example: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                healing:
                    type: number
                    description: Healing
                    default: 0
                    example: 12.6
                    format: double
                id:
                    type: string
                    description: ID is the unique id of the Item.
                    example: 123abc
                name:
                    type: string
                    description: Name
                    example: Boots of travel
                protection:
                    type: number
                    description: Protection
                    default: 0
                    example: 65.21
                    format: double
            description: A StoredItem describes a Item retrieved by the db.
            example:
                damage: 37.8267
                description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                healing: 12.6
                id: 123abc
                name: Boots of travel
                protection: 65.21
            required:
                - id
                - name
                - damage
                - healing
                - protection
        NotFound:
            type: object
            properties:
                id:
                    type: string
                    description: ID of missing resource
                    example: Et vitae et aperiam quis repudiandae.
                message:
                    type: string
                    description: Message of error
                    example: resource 1 not found
            description: Character not found
            example:
                id: Veniam voluptas sed.
                message: resource 1 not found
            required:
                - message
                - id
        StoredCharacter:
            type: object
            properties:
                description:
                    type: string
                    description: Description
                    example: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                experience:
                    type: number
                    description: Experience
                    example: 65.21
                    format: double
                health:
                    type: number
                    description: Health
                    example: 12.6
                    format: double
                id:
                    type: string
                    description: ID is the unique id of the character.
                    example: 123abc
                name:
                    type: string
                    description: Name
                    example: Arc Warden
            example:
                description: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                experience: 65.21
                health: 12.6
                id: 123abc
                name: Arc Warden
            required:
                - id
                - name
                - health
                - experience
        StoredCharacterResponseTiny:
            type: object
            properties:
                experience:
                    type: number
                    description: Experience
                    example: 65.21
                    format: double
                health:
                    type: number
                    description: Health
                    example: 12.6
                    format: double
                id:
                    type: string
                    description: ID is the unique id of the character.
                    example: 123abc
                name:
                    type: string
                    description: Name
                    example: Arc Warden
            description: A StoredCharacter describes a character retrieved by the db. (tiny view)
            example:
                experience: 65.21
                health: 12.6
                id: 123abc
                name: Arc Warden
            required:
                - id
                - name
                - health
                - experience
        StoredCharacterResponseTinyCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredCharacterResponseTiny'
            description: ListResponseBody is the result type for an array of StoredCharacterResponse (tiny view)
            example:
                - experience: 65.21
                  health: 12.6
                  id: 123abc
                  name: Arc Warden
                - experience: 65.21
                  health: 12.6
                  id: 123abc
                  name: Arc Warden
        StoredInventory:
            type: object
            properties:
                characterId:
                    type: string
                    description: CharacterId
                    example: 123abc
                id:
                    type: string
                    description: ID is the unique id of the inventory.
                    example: 123abc
                items:
                    type: array
                    items:
                        $ref: '#/components/schemas/JSON'
                    description: Character items
                    example:
                        - damage: 37.8267
                          description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                          healing: 12.6
                          id: 123abc
                          name: Boots of travel
                          protection: 65.21
                        - damage: 37.8267
                          description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                          healing: 12.6
                          id: 123abc
                          name: Boots of travel
                          protection: 65.21
                        - damage: 37.8267
                          description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                          healing: 12.6
                          id: 123abc
                          name: Boots of travel
                          protection: 65.21
            example:
                characterId: 123abc
                id: 123abc
                items:
                    - damage: 37.8267
                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
            required:
                - id
                - characterId
        StoredInventoryResponseTiny:
            type: object
            properties:
                characterId:
                    type: string
                    description: CharacterId
                    example: 123abc
                id:
                    type: string
                    description: ID is the unique id of the inventory.
                    example: 123abc
                items:
                    type: array
                    items:
                        $ref: '#/components/schemas/StoredItemResponseTiny'
                    description: Character items
                    example:
                        - damage: 37.8267
                          healing: 12.6
                          id: 123abc
                          name: Boots of travel
                          protection: 65.21
                        - damage: 37.8267
                          healing: 12.6
                          id: 123abc
                          name: Boots of travel
                          protection: 65.21
            description: A StoredInventory describes a StoredInventory retrieved by the db. (tiny view)
            example:
                characterId: 123abc
                id: 123abc
                items:
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
            required:
                - id
                - characterId
        StoredInventoryResponseTinyCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredInventoryResponseTiny'
            description: ListResponseBody is the result type for an array of StoredInventoryResponse (tiny view)
            example:
                - characterId: 123abc
                  id: 123abc
                  items:
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                - characterId: 123abc
                  id: 123abc
                  items:
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                - characterId: 123abc
                  id: 123abc
                  items:
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                - characterId: 123abc
                  id: 123abc
                  items:
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
                    - damage: 37.8267
                      healing: 12.6
                      id: 123abc
                      name: Boots of travel
                      protection: 65.21
        StoredItemResponseTiny:
            type: object
            properties:
                damage:
                    type: number
                    description: Damage
                    default: 0
                    example: 37.8267
                    format: double
                healing:
                    type: number
                    description: Healing
                    default: 0
                    example: 12.6
                    format: double
                id:
                    type: string
                    description: ID is the unique id of the Item.
                    example: 123abc
                name:
                    type: string
                    description: Name
                    example: Boots of travel
                protection:
                    type: number
                    description: Protection
                    default: 0
                    example: 65.21
                    format: double
            description: A StoredItem describes a Item retrieved by the db. (tiny view)
            example:
                damage: 37.8267
                healing: 12.6
                id: 123abc
                name: Boots of travel
                protection: 65.21
            required:
                - id
                - name
                - damage
                - healing
                - protection
        StoredItemResponseTinyCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredItemResponseTiny'
            description: ShowItemResponseBody is the result type for an array of StoredItemResponse (tiny view)
            example:
                - damage: 37.8267
                  healing: 12.6
                  id: 123abc
                  name: Boots of travel
                  protection: 65.21
                - damage: 37.8267
                  healing: 12.6
                  id: 123abc
                  name: Boots of travel
                  protection: 65.21
        UpdateRequestBody:
            type: object
            properties:
                character:
                    $ref: '#/components/schemas/AddRequestBody'
            example:
                character:
                    description: A splintered fragment of the same primordial power as the Ancients themselves, Zet endeavors to end the disharmony among the warring factions through whatever means necessary. Solitary foes are thrown into a volatile state of Flux, ripping away their health over time. Distorting space to generate a Protective Field sheltering around allies, evading and attacking with greater efficiency. Zet summons Spark Fragments of its former self that circles in place, and seek out nearby foes. Is there one Arc Warden, or two? Armed with the original's items and abilities, the Self's Tempest Double duplicates each spell and every attack, bringing twice the chaos to any fight.
                    experience: 65.21
                    health: 12.6
                    name: Arc Warden
            required:
                - character
        UpdateRequestBody2:
            type: object
            properties:
                item:
                    $ref: '#/components/schemas/AddRequestBody2'
            example:
                item:
                    damage: 37.8267
                    description: Boots of Travel is an item purchasable at the Base Shop, under Accessories. It can be upgraded by purchasing the recipe again.
                    healing: 12.6
                    name: Boots of travel
                    protection: 65.21
            required:
                - item
tags:
    - name: character
      description: Public HTTP frontend
    - name: inventory
      description: Public HTTP frontend
    - name: item
      description: Public HTTP frontend
    - name: swagger
      description: The swagger service serves the API swagger definition.
